name: Remove workflow number two
on:
  schedule: [{ cron: "0 0 * * *" }] # Schedule to run the workflow every 1 hour
  workflow_dispatch:
    inputs:
      repository_owner:
        default: long18
        description: Name of owner
        required: true
        type: string
      repository_name:
        default: long18
        description: Name of repository
        required: true
        type: string

jobs:
  clean:
    name: Clean ${{ inputs.workflow-name }}
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - uses: christosgalano/delete-workflow-runs@v1.0.0
        with:
          owner: ${{ inputs.repository_owner }}
          repo: ${{ inputs.repository_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
